name: nub_book_sharing
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.1.0
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  staggered_grid_view_flutter: ^0.0.4
  url_launcher: ^6.1.10
  flutter_svg: ^1.1.0
  path_provider: ^2.0.9

  cached_network_image: ^3.2.0
  lottie: ^2.3.0
  dropdown_button2: ^2.3.9
  share_plus: ^4.5.3
  carousel_slider: ^4.2.1

  #page transition
  page_transition: ^2.1.0

  #image_picker:
  image_picker: ^1.0.7
  extended_image: ^8.0.0
  extended_image_library: ^4.0.0

  #for text scanner
  google_mlkit_text_recognition: ^0.11.0
  screenshot: ^2.3.0

  #for time picker
  time_picker_spinner:
    path: ./plugins/time_picker_spinner


  #for firebase_ui_auth:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  random_string: ^2.3.1

  firebase_database: ^10.1.0
  google_sign_in: ^6.0.2
  font_awesome_flutter: ^10.6.0


  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^11.6.0

  # For showing Emojis
  emoji_picker_flutter: ^1.5.1

  # For accessing firebase messaging (Push Notification)
  firebase_messaging: ^14.7.10

  # For calling RestAPIs
  http: ^1.0.0

  # For creating notification channel
  flutter_notification_channel: ^2.0.0

  # For storing images into gallery
#  gallery_saver: ^2.3.2

  flutter_secure_storage: ^9.0.0
  package_info_plus: ^5.0.1

  #for schedulers calender_picker:
  easy_date_timeline:
    path: ./plugins/easy_date_timeline



 #list view
  smooth_list_view: ^1.0.4

  #for dotted border
  dotted_border: ^2.1.0

  #device_info_plus:
  device_info_plus: ^9.1.1


  #for permission handle:
  permission_handler: ^10.2.0

  #percentage
  percent_indicator: ^4.2.3
 #shimmer
  shimmer: ^3.0.0
  
  #for audioAble text
  flutter_tts: ^3.8.5
  file_picker: ^6.1.1
  pdf: ^3.10.8
  pdf_text:
    path: ./plugins/flutter-pdf-text




#for text to speech_balloon:

  flutter_pdfview: ^1.3.2
  uuid: ^4.1.0
  loading_animation_widget: ^1.2.1
 # for local notification
  flutter_local_notifications: 9.4.0
  awesome_notifications:

  #for animated drawer
  flutter_zoom_drawer: ^3.2.0
  awesome_drawer_bar: ^1.2.0
  flutter_platform_widgets: ^6.1.0


#  pdf_to_text2:
#    path: ./plugins/pdf_to_text2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/language/
    - assets/svg/
    - assets/lottie/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
